# platform :ios, '9.0'

target 'SHUxProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SHUxProject
  pod 'SnapKit', '~> 3.0.0'
  pod 'Reusable'
  pod 'Then'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HandyJSON'
end
